### ISSUE TITLE
Cafe-dsl sample not working

### ISSUE THREAD

**Issue by stefsp7** [spring-projects/spring-integration-samples#195]
It seems that after the route call the flow does not go back to the main flow (.defaultOutputToParentFlow() seems not to be working) and the commands after the route are never being executed.

**Comment by stefsp7** [comment]
@artembilan I tried .publishSubscribeChannel and .subscribe before .route and it worked, but i don't know if this is the right approach.

**Comment by artembilan** [comment]
Yeah! That is one of the solution.

Good catch, @stefsp7 !

So, well the problem isn't with the `defaultOutputToParentFlow()`, but with the sample which uses that feature for nothing. But at the same time the sample has lost its purpose after some changes in the Java DSL.

Not sure that we should reinstate that behavior, but at least there is a workaround like `.bridge(null)` in the end of each sub-flow. Just because it is better to explicitly request a return to the main flow, rather than do that unconditionally as it was before.

The  `defaultOutputToParentFlow()` has appear there in the sample really lightly.

Please, don't hesitate to provide a fix for that sample as a contribution!
