### ISSUE TITLE
spring-kafka without spring-boot

### ISSUE THREAD

**Issue by amolahinge** [spring-projects/spring-integration-samples#230]
is it possible to use spring-kafka or spring-integration-kafka without using spring-boot.
I have implemented producer without spring-boot,
but somehow not able to find consumer alternative i.e. @KafkaListener (spring-kafka)
Any help on this is useful. 

Is there any existing repo which has this implemented?
Also, are there any disadvantages of using spring instead of spring-boot.

In our use case, we want to use Kafka as a library and hence wants to use spring.

**Comment by artembilan** [comment]
GitHub is not a place where we handle questions.
Consider in the future to ask them on StackOverflow.

For disadvantages you need really to read Spring Boot [Reference Manual](https://spring.io/projects/spring-boot) and some existing book about it.

For the `@KafkaListener` without Spring Boot, please, read Spring Kafka [Reference Manual](https://docs.spring.io/spring-kafka/docs/2.1.7.RELEASE/reference/html/_introduction.html#_with_java_configuration).

The Spring Integration Java DSL for Kafka also can be used without Spring Boot. The options are still the same like in the reference manual above, but you configure `IntegrationFlow` beans via `Kafka` factory instead of the `@KafkaListener`.
