### ISSUE TITLE
gradlew :rest-http:build does not generate war

### ISSUE THREAD

**Issue by jmdopereiro** [spring-projects/spring-integration-samples#241]
The readme.md file of the intermediate/rest-http project says that running gradlew :rest-http:build should generate the war. After I run the command I get the following output but no war under target/ (with maven package a jar is generated):

Joses-MacBook-Air:spring-integration-samples jmd$ ./gradlew :rest-http:build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
6 actionable tasks: 1 exe

Thanks

**Comment by artembilan** [comment]
Thanks for the pointer.
Has been fixed in the linked commit.
The issue was that we have missed a `war` plugin to be included to WEB-aware projects.
also I've reinstated Gretty plugin in its new version. 
Now you can run these web apps from the build without deploying them to the external Servlet container.

Please, study also how to properly comment in GitHub: https://help.github.com/articles/basic-writing-and-formatting-syntax/
